exclude: '(\.golden|package-lock\.json|/abis/.*\.json|\.plutus|\.hash|\.address)$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-symlinks
        stages: [commit]
      - id: destroyed-symlinks
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        stages: [commit]
        additional_dependencies:
          - prettier@2.6.2
          - prettier-plugin-solidity@1.0.0-beta.19
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        stages: [commit]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.17.1
    hooks:
      - id: check-github-actions
        stages: [commit]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        stages: [commit]
  - repo: https://github.com/sk-saru/github-artifacts
    rev: c377b3d4c3a89cd78fc750e7aa8608dcba7811bc
    hooks:
      - id: fourmolu
        stages: [commit]
